"""Run the Electrimight dataset pipeline and reproducibility checks end to end."""

from __future__ import annotations

import argparse
import json
from pathlib import Path
from typing import Any

import pandas as pd

from src.data_assertions import run_pipeline_assertions
from src.eda_decision_support import build_decisions, write_outputs
from src.gold.ablation_study import run_ablation
from src.gold.generate_figures import main as generate_figures_main
from src.gold.pipeline import ElectrimightPipeline
from src.project_insights import (
    DEFAULT_ABLATION_PATH,
    DEFAULT_GAN_STATS_PATH,
    DEFAULT_GOLD_PATH,
    DEFAULT_OUTPUT_PATH,
    DEFAULT_PIPELINE_STATS_PATH,
    _forecast_table,
    _proxy_cv_table,
    build_summary,
    write_markdown,
)
from src.utils import GOLD_DIR, PIPELINE_METADATA_DIR, PROJECT_ROOT


FIGURES_DIR = PROJECT_ROOT / "references" / "report-guides" / "figures"
SYNTHETIC_PATH = GOLD_DIR / "steel_synthetic_gan.csv"


def _write_json(path: Path, payload: dict[str, Any]) -> None:
    """Write JSON metadata with explicit UTF-8 encoding."""
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(json.dumps(payload, ensure_ascii=False, indent=2), encoding="utf-8")


def _bool_count(df: pd.DataFrame, column: str) -> int:
    """Count truthy values in a boolean-like column."""
    if column not in df.columns:
        return 0
    series = df[column]
    if series.dtype == bool:
        return int(series.sum())
    if pd.api.types.is_numeric_dtype(series):
        return int(series.fillna(0).astype(float).gt(0).sum())
    return int(series.astype(str).str.lower().isin({"true", "1", "yes", "y"}).sum())


def build_pipeline_stats(df: pd.DataFrame) -> dict[str, Any]:
    """Build compact metadata for the final dataset artifact."""
    n_rows = int(len(df))
    any_count = _bool_count(df, "anomaly_any")
    return {
        "final_shape": [n_rows, int(len(df.columns))],
        "n_idling": _bool_count(df, "anomaly_idling"),
        "n_leakage": _bool_count(df, "anomaly_leakage"),
        "n_overload": _bool_count(df, "anomaly_overload"),
        "n_any_anomaly": any_count,
        "any_anomaly_pct": float(any_count / n_rows * 100) if n_rows else 0.0,
        "metadata_note": "Generated by python -m src.run_all.",
    }


def write_verification_summary(df: pd.DataFrame) -> dict[str, Any]:
    """Run post-labeling assertions and write a verification summary."""
    assertions = run_pipeline_assertions(df, stage="post_labeling", strict=False)
    payload = {
        "assertions": assertions,
        "pytest": {"summary": "Run python -m pytest for full unit-test verification."},
    }
    _write_json(PIPELINE_METADATA_DIR / "verification_summary.json", payload)
    return payload


def run_project_insights() -> None:
    """Regenerate the Markdown insight report from current metadata."""
    summary = build_summary(
        gold_path=DEFAULT_GOLD_PATH,
        ablation_path=DEFAULT_ABLATION_PATH,
        pipeline_stats_path=DEFAULT_PIPELINE_STATS_PATH,
        gan_stats_path=DEFAULT_GAN_STATS_PATH,
    )
    ablation = pd.read_csv(DEFAULT_ABLATION_PATH, encoding="utf-8")
    forecast = _forecast_table(ablation)
    proxy_full = _proxy_cv_table(ablation, "full")
    proxy_rule_free = _proxy_cv_table(ablation, "rule_free")
    write_markdown(summary, DEFAULT_OUTPUT_PATH, forecast, proxy_full, proxy_rule_free)


def parse_args() -> argparse.Namespace:
    """Parse command-line options for reproducible pipeline execution."""
    parser = argparse.ArgumentParser(description="Run DS108 Electrimight end to end.")
    parser.add_argument("--with-gan", action="store_true", help="Also train FC-GAN.")
    parser.add_argument("--gan-epochs", type=int, default=2000)
    parser.add_argument("--n-synthetic", type=int, default=500)
    parser.add_argument("--skip-ablation", action="store_true")
    parser.add_argument("--skip-figures", action="store_true")
    parser.add_argument("--skip-insights", action="store_true")
    return parser.parse_args()


def main() -> None:
    """Run pipeline, metadata checks, ablation, figures, and insight artifacts."""
    args = parse_args()
    PIPELINE_METADATA_DIR.mkdir(parents=True, exist_ok=True)

    pipeline = ElectrimightPipeline(
        log_level="INFO",
        use_gan=args.with_gan,
        gan_epochs=args.gan_epochs,
        n_synthetic=args.n_synthetic,
    )
    final_df = pipeline.run_pipeline()

    _write_json(PIPELINE_METADATA_DIR / "pipeline_stats.json", build_pipeline_stats(final_df))
    write_verification_summary(final_df)

    if not args.skip_ablation:
        run_ablation(
            input_path=DEFAULT_GOLD_PATH,
            synthetic_path=SYNTHETIC_PATH,
            output_dir=PIPELINE_METADATA_DIR,
            figures_dir=FIGURES_DIR,
        )

    if not args.skip_figures:
        generate_figures_main()

    decisions = build_decisions()
    write_outputs(decisions)

    if not args.skip_insights and DEFAULT_ABLATION_PATH.exists():
        run_project_insights()

    print("Electrimight run_all completed.")
    print(f"Gold dataset: {DEFAULT_GOLD_PATH}")
    print(f"Pipeline metadata: {PIPELINE_METADATA_DIR}")


if __name__ == "__main__":
    main()
